$schema: https://azuremlschemas.azureedge.net/latest/onlineDeployment.schema.json
name: taxi-online-dp
endpoint_name: taxi-online-devtmlopspocmtsprod
model: azureml:taxi-model@latest
code_configuration:
  code: ./
  scoring_script: score.py
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
instance_type: Standard_DS3_V2
instance_count: 1
